### ISSUE TITLE
Prevent Active initial 

### ISSUE THREAD

**Issue by hyunjimoon** [Data4DM/BayesSD#63]
![image](https://user-images.githubusercontent.com/30194633/196495584-9a84d860-1394-4e40-af25-d35b2a55183b.png)

**Comment by hyunjimoon** [comment]
![image](https://user-images.githubusercontent.com/30194633/196499376-0526bceb-846c-4b43-b7ef-333ad35916c1.png)

**Comment by tomfid** [comment]
I think this active initial warning is _probably_ ignorable. It often happens when there are random inputs and you've used the active initial function to break a simultaneous initial condition loop. The random draw in the initialization step differs from the random draw at time 0, so the stocks may get initialized to something different from the equilibrium around the time 0 flows. That may not be a problem.

The only solution might be to get rid of the ACTIVE INITIAL statements.
